# Generated by Django 4.1 on 2022-08-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitasModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, unique_for_month='data')),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
            ],
            options={
                'db_table': 'receitas',
            },
        ),
        migrations.DeleteModel(
            name='Receitas',
        ),
    ]
