# Generated by Django 4.1 on 2022-08-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesasmodel',
            name='descricao',
            field=models.CharField(max_length=255, unique_for_month=models.DateTimeField()),
        ),
    ]
