# Generated by Django 4.1 on 2022-08-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_alter_despesasmodel_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesasmodel',
            name='descricao',
            field=models.CharField(max_length=255, unique_for_month='data'),
        ),
    ]
