# Generated by Django 4.1 on 2022-08-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_despesasmodel_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesasmodel',
            name='categoria',
            field=models.CharField(choices=[('Alimentação', 'Alimentacao'), ('Saúde', 'Saude'), ('Moradia', 'Moradia'), ('Transporte', 'Transporte'), ('Educação', 'Educacao'), ('Lazer', 'Lazer'), ('Imprevistos', 'Imprevistos'), ('Outras', 'Outras')], default='Outras', max_length=11),
        ),
    ]
